language: python

python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install pylint
  - pip install codecov
script:
  - pylint --rcfile=.pylintrc-shush braggy/backend/
  - pytest --cov-report term --cov=braggy/backend
after_success:
  - codecov